FROM ubuntu
#RUN apt-get update -y
#RUN apt-get install -y curl
#RUN curl https://wasmtime.dev/install.sh -sSf | bash
#RUN export PATH="$HOME/.wasmtime:$PATH"
WORKDIR /app
COPY fileserver.wasm fileserver.wasm
COPY wasmtime wasmtime
COPY public public
EXPOSE 8080
CMD ./wasmtime run --tcplisten 0.0.0.0:8080 --dir=. --env 'LISTEN_FDS=1' fileserver.wasm 0.0.0.0 8080 ./public
