FROM ubuntu:22.10

WORKDIR /app


# COPY wasmedge lib
COPY --from=us.icr.io/polyglotwasmbench/sdk-wrapper-buildstage-time /root/.wasmedge/lib /root/.wasmedge/lib
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/.wasmedge/lib

# Copy WASM module
COPY --from=us.icr.io/polyglotwasmbench/sdk-wasm-library-time:latest /wasms/file-server/rust/wasm/echo/main.wasm main.wasm


#  Copy Wrapper
COPY --from=us.icr.io/polyglotwasmbench/sdk-wrapper-library-time:latest /wrappers/output/rust_wasmtime_wrapper rust_wasmtime_wrapper

ENV LISTEN_FDS=1

CMD [ "./rust_wasmtime_wrapper", "main.wasm", "127.0.0.1", "8080"]
