FROM ubuntu:22.10

WORKDIR /app


# COPY wasmedge lib
COPY --from=us.icr.io/polyglotwasmbench/sdk-wrapper-buildstage-time /root/.wasmedge/lib /root/.wasmedge/lib
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/.wasmedge/lib

# Copy WASM module
COPY --from=us.icr.io/polyglotwasmbench/sdk-wasm-library-time:latest /wasms/sort/rust/main.wasm main.wasm


#  Copy Wrapper
COPY --from=us.icr.io/polyglotwasmbench/sdk-wrapper-library-time:latest /wrappers/output/go_wasmtime_wrapper go_wasmtime_wrapper


CMD [ "./go_wasmtime_wrapper", "main.wasm"]
